# -*- coding: utf-8 -*-
"""set.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11r-K5vB_kx0Gm9AiHpGzeJzgJYDd6f2n
"""

emptyset = set()
print("Empty set")
print(emptyset)

s1 = {10,50,20}
print(s1)
print(type(s1))

s2 = {"a","b","c"}
print(s2)
print(type(s2))

s2.add("d")
print(s2)

s3 = set(["Prodi","Informatika","UIN Sunan Kalijaga"])
print(s3)

people = {"Jay","Idrish","Archi"}
vampires = {"Karan","Arjun"}
dracula = {"Deepanshu","Raj"}

population1 = people.union(vampires)
population2 = people|dracula

print("\nUnion using union() function")
print(population1)

print("\nUnion using '|' operator")
print(population2)

print("\nMembership test")
print('Archi' in people)

print("\nSubset test")
print(vampires.issubset(population1))

print("\nSuperset test")
print(population2.issuperset(people))

set1 = set()
set2 = set()

for i in range(5):
  set1.add(i)

for i in range(3,9):
  set2.add(i)

print(set1)
print(set2)

set3 = set1.intersection(set2)
print("\nIntersection using intersection() function")
print(set3)

set3 = set1 & set2
print("\nIntersection using '&' operator")
print(set3)

set4 = set1.difference(set2)
print("\nDifference of two sets using difference() function")
print(set4)

set4 = set1 - set2
print("\nDifference of two sets using '-' operator")
print(set4)

set5 = set2.difference(set1)
print("\nDifference of two sets using difference() function")
print(set5)

set5 = set2 - set1
print("\nDifference of two sets using '-' operator")
print(set5)

relation1 = {("Karan","Deenpashu"), ("Arjun","Raj")}
print("\nRelation")
print(relation1)